### ISSUE TITLE
Update domain

### ISSUE THREAD

**Issue by Kartikiscool** [IndusAryan/Aryans-Cloudstream-Extensions#13]
Prmovies.wine is blocked the new domain is prmovies.dog

In future add a configuration button in plugin to update domain.

Jay Shree Ram

**Comment by Kartikiscool** [comment]
@IndusAryan  an you please add another website for Indian tv serials and/or live channels via Jio tv api (works in kodi)

Thank you for your immediate attention

**Comment by IndusAryan** [comment]
no requests ,i don't make any extensions this is continued extension from old repo that was not maintained.
