### ISSUE TITLE
Website request and help regarding extension 

### ISSUE THREAD

**Issue by ChandanKSDeveloper** [IndusAryan/Aryans-Cloudstream-Extensions#14]
Can you add this sites:- 
1. [Toonstream](https://toonstream.net/)
2. [Netfilm](https://netfilm.app/)

----------------------------------------------------------
Can you tell me how can I start making my own extensions. Any course or YouTube playlist to learn web scrapping for this. 

And I develop an extension python instead of kotlin, will it work on Android??

**Comment by IndusAryan** [comment]
i am not making any extensions, actually no one is actively making them except these 2 people. open issue here as both sites are great they will probably work on it. 
https://github.com/Rowdy-Avocado/Rowdycado-Extensions

to make extensions you need to know some programming in any good language like java python or js, but to make an extension, only KOTLIN is used for cs3. but its easy language if you already have coding background.

First follow the tutorial https://recloudstream.github.io/csdocs/devs/gettingstarted/

then fork my extension so you dont get any error, and start creeating extension, PR movies is an easy start to understand how things works, and join cloudstream discord dev chat for help.
