### ISSUE TITLE
Prmovie - Plugins Not Working

### ISSUE THREAD

**Issue by Jandu-jaja** [IndusAryan/Aryans-Cloudstream-Extensions#20]
I have already cloned the all different proxy sites and domains but still not working.

Thanks in advance.

And also I want to learn basic things about extension in cloud stream (how it works and how you can create it). if there any way we can connect I want help to create new extension and maintain it.

**Comment by IndusAryan** [comment]
https://recloudstream.github.io/csdocs/devs/gettingstarted/
join discord and learn kotlin programming
